# Generated by Django 2.1 on 2019-01-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ora_dual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=12)),
            ],
        ),
    ]
