# Generated by Django 2.1 on 2019-01-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ora_dual', '0002_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(db_column='cp', max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_type',
            field=models.CharField(choices=[(1, 'Super User'), (2, 'VIP User'), (3, 'Normal User')], default=3, max_length=32),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(blank=True, help_text='username', max_length=32, verbose_name='用户名'),
        ),
    ]
