# Generated by Django 2.1 on 2019-01-15 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ora_dual', '0004_userinfo_user_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user_group',
        ),
    ]
