# Generated by Django 2.1 on 2019-01-15 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ora_dual', '0005_remove_userinfo_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_group',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ora_dual.UserGroup'),
            preserve_default=False,
        ),
    ]
