# Generated by Django 2.1 on 2019-01-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ora_dual', '0007_auto_20190115_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='loadmetric_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_number', models.IntegerField(max_length=10)),
                ('snap_date', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('elapse_min', models.FloatField()),
                ('dbtime_min', models.FloatField()),
                ('redo', models.FloatField()),
                ('redo_second', models.FloatField()),
                ('logical', models.FloatField()),
                ('logical_second', models.FloatField()),
                ('physical', models.FloatField()),
                ('physical_second', models.FloatField()),
                ('execs', models.FloatField()),
                ('execs_second', models.FloatField()),
                ('parse', models.FloatField()),
                ('parse_second', models.FloatField()),
                ('hardware', models.FloatField()),
                ('harware_second', models.FloatField()),
                ('trans', models.FloatField()),
                ('trans_second', models.FloatField()),
            ],
        ),
    ]
