# Generated by Django 2.1 on 2019-01-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ora_dual', '0008_loadmetric_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='spaceusage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateField()),
                ('tablespace_name', models.FloatField()),
                ('total', models.FloatField()),
                ('free', models.FloatField()),
                ('used', models.FloatField()),
                ('percent', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='loadmetric_hour',
            name='instance_number',
            field=models.IntegerField(),
        ),
    ]
