# Generated by Django 2.1 on 2019-01-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ora_dual', '0009_auto_20190121_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceusage',
            name='tablespace_name',
            field=models.CharField(max_length=10),
        ),
    ]
