# Generated by Django 2.1 on 2019-01-23 08:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ora_dual', '0010_auto_20190121_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceusage',
            name='collect_time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
