# Generated by Django 2.1 on 2019-01-23 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ora_dual', '0013_auto_20190123_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spaceusage',
            name='data_time',
        ),
    ]
