# Generated by Django 2.1 on 2019-01-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ora_dual', '0014_remove_spaceusage_data_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='spacechange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_time', models.CharField(max_length=30)),
                ('tablespace_name', models.CharField(max_length=10)),
                ('tablespace_usedsize_kb', models.FloatField()),
                ('tablespace_size_kb', models.FloatField()),
                ('DIFF_KB', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='system_metric_period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_time', models.CharField(max_length=30)),
                ('begin_time', models.CharField(max_length=30)),
                ('end_time', models.CharField(max_length=30)),
                ('metric_name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('metric_desc', models.CharField(max_length=100)),
            ],
        ),
    ]
