# Generated by Django 2.1 on 2019-01-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ora_dual', '0015_spacechange_system_metric_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system_metric_period',
            name='metric_desc',
        ),
        migrations.RemoveField(
            model_name='system_metric_period',
            name='value',
        ),
        migrations.AddField(
            model_name='system_metric_period',
            name='data_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='system_metric_period',
            name='metric_average',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='system_metric_period',
            name='metric_squares',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='system_metric_period',
            name='metric_standard',
            field=models.FloatField(null=True),
        ),
    ]
