# Generated by Django 2.1 on 2019-01-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ora_dual', '0016_auto_20190124_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_metric_period',
            name='data_value',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
